### Sistem Akışı

1. Proje tanımı (Markdown)
2. Veriyi üret
3. Temizle
4. Analiz et
5. Sonuçları yazdır
6. Excel çıktısı al

Örnek çıktı:

```
Toplamsatış:4.820.000TL
Enkârlı şehir: İstanbul
Eniyiay:Mart
Risklibölge:DoğuAnadolu
Excelraporuoluşturuldu.

```

## Proje Tanıtımı

Bu proje, kurumsal satış verisini uçtan uca işleyen mini bir karar destek sistemi örneğidir. Sistem; sentetik veri üretimi, veri temizleme, analitik hesaplamalar ve yönetici özeti üretimi adımlarını tek bir akışta birleştirir.

### Amaç
- Satış performansını şehir, ürün ve ay bazında görünür hale getirmek
- Eksik ve uç değerli verilerle çalışabilen dayanıklı bir analiz hattı kurmak
- Karar almayı kolaylaştıran özet bir rapor ve Excel çıktısı üretmek

### Kullanılan Teknolojiler
- **Python**
- **NumPy**: vektörel hesaplama ve istatistik
- **Pandas**: veri temizleme, gruplayarak analiz ve raporlama

### İş Akışı
1. `generate_data()` ile örnek satış verisi oluşturulur
2. `clean_data()` ile eksik veriler doldurulur ve veri normalize edilir
3. `analyze_data()` ile şehir/ürün/ay kırılımlarında satış analizi yapılır
4. `generate_report()` ile en iyi/en zayıf performans metrikleri üretilir
5. Sonuçlar ekrana yazdırılır ve `sales_report.xlsx` olarak dışa aktarılır

### Üretilen Çıktılar
- Şehir bazlı toplam satış
- Ürün bazlı toplam satış
- Ay bazlı satış trendi
- Ortalama satış ve standart sapma
- Yönetici özeti (en iyi şehir, en kârlı ürün, en iyi ay vb.)

In [1]:
from data_generator import generate_data
from preprocessing import clean_data
from analytics import analyze_data
from reporting import generate_report

In [3]:
data = generate_data()  
data

     CustomerID Product      City  SalesAmount    Month
0          5500  Ürün D     İzmir   184.932139    Nisan
1          4838  Ürün C    Ankara   780.355553     Mart
2          9963  Ürün A  İstanbul   475.529799  Haziran
3          8862  Ürün A  İstanbul   856.165867    Nisan
4          1186  Ürün B  İstanbul   291.566040     Ocak
..          ...     ...       ...          ...      ...
995        3147  Ürün A  İstanbul   259.251157  Haziran
996        3200  Ürün B     İzmir          NaN     Mart
997        1310  Ürün B     İzmir   149.981122    Mayıs
998        9435  Ürün A  İstanbul   343.797911    Nisan
999        1326  Ürün B    Ankara    74.080538  Haziran

[1000 rows x 5 columns]

In [4]:
clean_data = clean_data(data)
clean_data

Eksik Veriler:
CustomerID       0
Product          0
City             0
SalesAmount    100
Month            0
dtype: int64

c:\Users\talsh\OneDrive\Masaüstü\enterprise_sales_system\preprocessing.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SalesAmount'].fillna(df['SalesAmount'].mean(), inplace=True)

     CustomerID Product      City  SalesAmount    Month  SalesAmountWithVAT
0          5500  ürün d     İzmir   184.932139    Nisan          218.219924
1          4838  ürün c    Ankara   780.355553     Mart          920.819553
2          9963  ürün a  İstanbul   475.529799  Haziran          561.125162
3          8862  ürün a  İstanbul   856.165867    Nisan         1010.275723
4          1186  ürün b  İstanbul   291.566040     Ocak          344.047928
..          ...     ...       ...          ...      ...                 ...
995        3147  ürün a  İstanbul   259.251157  Haziran          305.916365
996        3200  ürün b     İzmir   745.760183     Mart          879.997016
997        1310  ürün b     İzmir   149.981122    Mayıs          176.977724
998        9435  ürün a  İstanbul   343.797911    Nisan          405.681535
999        1326  ürün b    Ankara    74.080538  Haziran           87.415034

[1000 rows x 6 columns]

In [6]:
city_sales, product_sales, month_sales, performance_scores = analyze_data(clean_data)
print("City Sales:", city_sales)
print("Product Sales:", product_sales)
print("Month Sales:", month_sales)
print("Performance Scores:", performance_scores)

City Sales: City
Ankara      173153.760765
Bursa       178231.531180
İstanbul    164634.239214
İzmir       229740.652227
Name: SalesAmount, dtype: float64
Product Sales: Product
ürün a    164335.360607
ürün b    191376.711210
ürün c    184124.877316
ürün d    205923.234253
Name: SalesAmount, dtype: float64
Month Sales: Month
Haziran    136208.430424
Mart       120492.673972
Mayıs      125247.860403
Nisan      102556.453137
Ocak       110749.965206
Şubat      150504.800245
Name: SalesAmount, dtype: float64
Performance Scores: {'mean_sales': np.float64(745.7601833863347), 'std_sales': np.float64(1151.925545512619)}

In [7]:
report = generate_report(city_sales, product_sales, month_sales, performance_scores)

In [8]:
report

{'Best City': 'İzmir',
 'Worst City': 'İstanbul',
 'Most Profitable Product': 'ürün d',
 'Least Profitable Product': 'ürün a',
 'Best Month': 'Şubat',
 'Worst Month': 'Nisan',
 'Average Sales': np.float64(745.7601833863347),
 'Sales Std Dev': np.float64(1151.925545512619)}

In [9]:
for key, value in report.items():
    print(f"{key}: {value}")

Best City: İzmir
Worst City: İstanbul
Most Profitable Product: ürün d
Least Profitable Product: ürün a
Best Month: Şubat
Worst Month: Nisan
Average Sales: 745.7601833863347
Sales Std Dev: 1151.925545512619

In [13]:
import pandas as pd
report_df = pd.DataFrame(list(report.items()), columns=['Metric', 'Value']) 
report_df.to_excel('sales_report.xlsx', index=False)
print("Excel raporu oluşturuldu.")

Excel raporu oluşturuldu.